### PR TITLE
Popup added on Contact page

### PR DESCRIPTION
**Pull request by singhcoder694**
#82 

Contact popup has been added to give error and success message on Clicking send button.
Screenshot 2023-12-16 104122
Screenshot 2023-12-16 104137

### CODE REVIEW

**Comment by Kritika30032002** [comment]
this mail will be sent to whom?

**Comment by singhcoder694** [comment]
This you can handle in the code, for now in this code I have mention my smtp server and mail so It will reach my Id. You may change it to your or organization mail so that they can see the user's message....
Screenshot 2023-12-16 175048
In the Screenshot just change the smpt username and password(generate from smtp website) and update **To**, to send it to respective mail....

**Comment by Kritika30032002** [comment]
change your email to sample@xyz.com

**Comment by singhcoder694** [comment]
Screenshot 2023-12-17 085553
Changed. Mail needs to be verified from smtp to start it functioning after that mailing would start....

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
