### PR TITLE
More blogs

### LINKED ISSUE #34: Add blogs
Add Blogs to the website which should be copyright free and self written.

### PR DESCRIPTION
**Pull request by alvin-dennis**
**Description**

This PR fixes #34

### CODE REVIEW

**Comment by Kritika30032002** [comment]
are the blogs copyright free?

**Comment by alvin-dennis** [comment]
@Kritika30032002 I referred Google. But not entirely

**Comment by Kritika30032002** [comment]
combination from multiple sources or from one website?

**Comment by alvin-dennis** [comment]
@alvin-dennis multiple sources

**Comment by alvin-dennis** [comment]
@Kritika30032002 are u merging it?

**Pull request merged**
