### PR TITLE
Logo Updated

### PR DESCRIPTION
**Pull request by saurabhgdeshmukh**
Screenshot 2023-12-12 at 11-51-48 Daily Journal
Screenshot 2023-12-12 at 11-51-39 Daily Journal

### CODE REVIEW

**Comment by saurabhgdeshmukh** [comment]
@Kritika30032002 logo changed please check it.

**Comment by Kritika30032002** [comment]
It should not have any copyright issue?

**Comment by saurabhgdeshmukh** [comment]
No, it doesn't have any.

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
