### PR TITLE
Fixed the command for cloning repo

### LINKED ISSUE #201: [Bug]: The Command line for cloning repo is not correct
### Contact Details

shadkhanxox@gmail,com

### What happened?

The command line needs to be fixed, the beginners contributor might get confused

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadyx6**
The Command line for cloning the repo should be blog_website. But it was blog-website. Please merge this and label gssoc on my PR

**Description**

This PR fixes #201

### CODE REVIEW

**Comment by Shadyx6** [comment]
I copy and pasted it into terminal and it was working fine, can you elaborate which link is not correct?
Thankyou for assigning me !

**Comment by Kritika30032002** [comment]
clone repo link should be [This](https://github.com/Kritika30032002/Blog_Website.git )

**Comment by Shadyx6** [comment]
I have fixed it in the latest commit !

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your contribution.

Do not forget to give a star to the repo.

**Comment by Shadyx6** [comment]
I have starred already, why you did not label the PR as gssoc-ext? I didn't got score for contributing🥲

**Comment by Shadyx6** [comment]
Please label the PR. So it get counted on my gssoc-ext score

**Pull request merged**
