### PR TITLE
closes #57

### LINKED ISSUE #57: feat : user profile section
Creating a user profile section allowing users to create profile wherein they can view and edit their personal information and can also see a list of blog posts created by that specific user on their profile. 
@Kritika30032002 please assign me this issue.

### PR DESCRIPTION
**Pull request by AishaAgarwal**
A profile section is created for users allowing them to even edit their profile. 
Also an optional login is set up where the users cn read the available blogs without loggin in ..but if they want to compose the blog , then sign in is required.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Displaying of composed blogs on website should require admin approval

**Comment by AishaAgarwal** [comment]
Can you please clarify once in detail ..

**Comment by Kritika30032002** [comment]
The person has to submit the blog for approval and after approval only it will be displayed on website

**Comment by AishaAgarwal** [comment]
understood ..will do so

**Pull request closed without merging**
