### PR TITLE
Added Contact Page

### LINKED ISSUE #29: Improve Contact-us page
Hey!
I want to improve contact-us page can you please assign me this under Hacktoberfest-accepted!

### PR DESCRIPTION
**Pull request by Nupur19nj**
Added the contact page!
Fixes #29

### CODE REVIEW

**Comment by Nupur19nj** [comment]
completed the task kindly verify and merge !

**Comment by Nupur19nj** [comment]
hey can you please merge the PR it's been 2 days!

**Comment by Kritika30032002** [comment]
show the changes


share the screenshot @Nupur19nj

**Comment by Nupur19nj** [comment]
image

**Comment by Nupur19nj** [comment]
can you please check fast! deadline is very close i need verification as well!

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
