### PR TITLE
display content of home in cards 

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Now the posts which are present in home page are displayed in **cards** with good **hovering effect**  : )

Here is the demo ---------------------->>>

https://github.com/Kritika30032002/Blog_Website/assets/127650446/7466ba99-4eab-482d-8047-d1c7d4f82eec

Once check it and merge it _Hacktoberfest-2023 : )

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Design of the card needs improvement

**Comment by Bharath-KumarReddy** [comment]
Hi , 
I changed the styles of cards In home page once check : )


https://github.com/Kritika30032002/Blog_Website/assets/127650446/dfd79cb2-9a6f-4b7f-b018-6689c507472d

**Comment by Kritika30032002** [comment]
resolve conflict

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
