### PR TITLE
✨issue #191 solved improved UI ✨

### PR DESCRIPTION
**Pull request by trahulprabhu38**
**Description**
 
the UI has been updated , @Kritika30032002 can you please review this .
thank you.

Screenshot 2024-10-13 at 12 18 49 AM
Screenshot 2024-10-13 at 12 19 18 AM
Screenshot 2024-10-13 at 12 25 14 AM

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Mention the issue number

**Comment by trahulprabhu38** [comment]
#191  @Kritika30032002 this is the issue,

**Comment by Kritika30032002** [comment]
Write like this

**Comment by T-Rahul-prabhu-38** [comment]
**
Screenshot 2024-10-20 at 11 22 00 AM
**

**Comment by trahulprabhu38** [comment]
@Kritika30032002 i fixed that

**Comment by trahulprabhu38** [comment]
Screenshot 2024-10-20 at 11 24 57 AM

**Comment by trahulprabhu38** [comment]
@Kritika30032002 can you please review this.

**Pull request closed without merging**
