### PR TITLE
feat: password validation optimized

### LINKED ISSUE #139: [Feature] Improper Password Handling
### Describe the feature you'd like to request

When someone tries to sign up with a password that doesnt meet the criteria , the form gets submitted and we are redirected to a very messy page where we are said to register once again
image

### Describe the solution you'd like

Instead of checking for the password requriements in the backend ,we can make it check for all the password checking in the frontend itself so that the user has a smoother experience.

### PR DESCRIPTION
**Pull request by Piyush-linux**
## :hand:  Description

This PR fixes #139 

- The work is done on Frontend for Validation of Password
- I've Used HTML Advance Attributes for `<input>` tag
- Regex pattern has been implemented

## :framed_picture:  Screen Shot

Screenshot_2024-04-01-12-22-06_1920x1080

### :link:   Resources 

- [Password Attribute](https://www.wufoo.com/html5/password-type/)
- [Regex](https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a)

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Have you tested it?

**Comment by Piyush-linux** [comment]
> Have you tested it?

Yo @Kritika30032002 ,
Yes It's working perfectly, but I also want to make certain changes into backend code, especially the error page it renders.
That Could be done in a different way !
Should I do it or this much is  enough.

**Comment by Kritika30032002** [comment]
just deal with entire password functionality and make it work correctly

**Comment by Piyush-linux** [comment]
Vokea

**Comment by Piyush-linux** [comment]
Yo @Kritika30032002 , Done

### Changes
- [x] Error Page Redesign
- [x] Frontend validation

**Pull request merged**
