### PR TITLE
I have  added sample blogs in blog.json and added a read blog button to read them

### PR DESCRIPTION
**Pull request by YashSachan2**
I have made the necessary changes as you asked in previous pr and now only blog.json have blogs which are read by app.js.

https://github.com/Kritika30032002/Blog_Website/assets/122620769/277e6068-f4f5-4a5f-9184-356ec35b58bf

please look into it and assign me the points

### CODE REVIEW

**Comment by Kritika30032002** [comment]
/blogs screen UI needs improvement.

Or you want this to do in next pr ?

**Comment by YashSachan2** [comment]
I can do it in the next pr. I guess it is a new enhancement problem.

**Comment by YashSachan2** [comment]
Could you tell a few points you are expecting in the UI

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by Kritika30032002** [comment]
> Could you tell a few points you are expecting in the UI

Proper display of short part of blogs on blogs screen

and detail page of each blogs, it should contain blog posted date, author, headline, and entire blog

**Comment by YashSachan2** [comment]
Will I get points for this pr?

**Comment by Kritika30032002** [comment]
given just now

**Comment by YashSachan2** [comment]
Thank you so much

**Comment by Kritika30032002** [comment]
Are your blogs copyright free ? @YashSachan2 
If yes, then add your name as author in blogs and add your linkedin and github id in blogs.json  file and make a pr

**Comment by YashSachan2** [comment]
Sure @Kritika30032002

**Pull request merged**
