### PR TITLE
Feat/improve blog detail page

### PR DESCRIPTION
**Pull request by timmySpark**
### **What was Added in this Branch**

**Redesigned the Blog Page: I enhanced the blog page by adding a designated spot for images. Now, users can see visually appealing thumbnails alongside blog titles. Additionally, I ensured that not only the "Read More" button but also the image and title link to the respective blog detail pages, enhancing user experience and navigation.**

Screenshot 2024-03-18 at 20 15 29

**Redesigned Blog Detail Page: I revamped the blog detail page to make it more descriptive and engaging**

Screenshot 2024-03-21 at 20 47 31

Screenshot 2024-03-21 at 20 47 49

**Enhanced Post-Blog Page Design: After users sign up and post a new blog, I included a designated spot where users can add an image when they create their own blog**

Screenshot 2024-03-21 at 20 49 21

This PR fixes issue #107 
These changes aim to improve user engagement, readability, and overall satisfaction with the blog platform.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
images should not have any copyright issue?

**Comment by timmySpark** [comment]
Another person was assigned the task of writing blogs, I just used these images for test purposes
The blogs will be overwritten, should I take it off?

**Comment by Kritika30032002** [comment]
overight can be alright but t should not have any copyright issue

**Comment by timmySpark** [comment]
okay, once the new blogs are written, I'll take down these ones.

any other change I need to make before the pr is good to be merged?

**Comment by timmySpark** [comment]
@Kritika30032002 , can the pr please be merged now ?

**Comment by Kritika30032002** [comment]
if the images are not copyright free, I can't merge

**Comment by timmySpark** [comment]
Okay. based on my research, unsplash images are copyright free and that's what I used for these designs

**Comment by Kritika30032002** [comment]
authors, images or published date

If you want to add these then you have to also update frontend of it to display then correctly

**Review by Kritika30032002 — APPROVED** [review]

**Pull request merged**
