### PR TITLE
Menu bar Added

### PR DESCRIPTION
**Pull request by saurabhgdeshmukh**
Screenshot (12)
Screenshot (11)

Menu updated for mobile view

### CODE REVIEW

**Comment by saurabhgdeshmukh** [comment]
@Kritika30032002 please check changes

**Comment by Kritika30032002** [comment]
Please refer to other websites to know how it should look like

**Comment by Kritika30032002** [comment]
you can ask me if have any doubt

**Comment by Kritika30032002** [comment]
screenshot ?

**Comment by saurabhgdeshmukh** [comment]
Screenshot (17)
Screenshot (18)

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Pull request merged**
