### PR TITLE
Made navbar responsive

### PR DESCRIPTION
**Pull request by mangalgithub**
Made the navbar responsive and toggleable on small devices and some styling to navbar.

### CODE REVIEW

**Comment by mangalgithub** [comment]
Here is the screenshot of the screen views of navbar.
In full screen

Screenshot 2023-10-03 151315

In small screen
Screenshot 2023-10-03 151332

After clicking the toggle button

Screenshot 2023-10-03 151343

**Comment by mangalgithub** [comment]
Hi! @Kritika30032002  I hope this improvement help in enhancing the project. Pls review this enhancement and discuss if any change needed in this else pls merge this in your project. Waiting for your response.

**Comment by Kritika30032002** [comment]
Great work But

In full screen  
Home, about  and contact should be in right side

**Comment by mangalgithub** [comment]
Hi! @Kritika30032002  I made the changes suggested by you. Pls review and merge this.
In full screen

image

In small screen

image

on clicking toggle button

image

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
