### PR TITLE
Recreated About page.

### PR DESCRIPTION
**Pull request by pankajsingh92533**

### CODE REVIEW

**Comment by pankajsingh92533** [comment]
Screenshot 2023-10-17 235305

Please review it.

**Comment by Kritika30032002** [comment]
Add a proper about page content rather than random text

**Comment by pankajsingh92533** [comment]
new about
Added content as per instruction. Please review it.

**Comment by Kritika30032002** [comment]
1. resolve conflicts
2. Design needs improvement

**Pull request closed without merging**
