### PR TITLE
[feat] Added in blog-site

### PR DESCRIPTION
**Pull request by PranjaliBhardwaj**
#108 #152 all overlapping of footer from all pages are fixed and signup with google OAuth credentials is also added in the signup page, 
After: 
Screenshot 2024-03-22 170754
Before: 
Screenshot 2024-03-22 124216
I have removed firebase config details due to security reasons, but I am also beginner and don't know if its okay, so if it is I can add those details too. @Kritika30032002

### CODE REVIEW

**Comment by Kritika30032002** [comment]
adding <br> for space is not a good practice. Look into another way.

**Comment by Kritika30032002** [comment]
also you should have separate pr for separate issue

**Comment by PranjaliBhardwaj** [comment]
@Kritika30032002 That issue wasn't that big so I didn't create a new pull request, but for future I will keep that in mind. I have used css now to avoid overlapping of footer and other page's content.

**Comment by Kritika30032002** [comment]
image


see the highlighted code line

**Comment by PranjaliBhardwaj** [comment]
> image
> 
> see the highlighted code line

So I should use margin instead to spaces?

**Comment by Kritika30032002** [comment]
yes

**Comment by PranjaliBhardwaj** [comment]
now its good. @Kritika30032002 Thankyou for your guidance and patience.

**Pull request closed without merging**
